// <auto-generated />
using System;
using Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Data.Migrations
{
    [DbContext(typeof(TestContext))]
    [Migration("20221201175124_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Model.PrizeRedemptionEntity", b =>
                {
                    b.Property<long>("RedemptionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("RedemptionId"));

                    b.Property<string>("AccountHolder")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("AccountNumber")
                        .HasColumnType("bigint");

                    b.Property<string>("AccountType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AgencyDigit")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AgencyNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("AwardWinningGames")
                        .HasColumnType("int");

                    b.Property<string>("BankName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BankNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CPF")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long?>("ContestNumber")
                        .HasColumnType("bigint");

                    b.Property<long?>("ContestNumberRef")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("CreatedTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("CurrentAccount")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CurrentAccountDocument")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Draw")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("Fee")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Game")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long?>("GroupCode")
                        .HasColumnType("bigint");

                    b.Property<string>("GroupName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HonorName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IP")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("IsAdministrator")
                        .HasColumnType("bit");

                    b.Property<decimal>("Jackpot")
                        .HasColumnType("money");

                    b.Property<decimal>("JackpotLimit")
                        .HasColumnType("money");

                    b.Property<long?>("LotteryId")
                        .HasColumnType("bigint");

                    b.Property<string>("LotteryName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("money");

                    b.Property<long?>("QuotaQuantity")
                        .HasColumnType("bigint");

                    b.Property<string>("RedemptionType")
                        .IsRequired()
                        .HasColumnType("varchar(100)");

                    b.Property<DateTime?>("RequestTime")
                        .HasColumnType("datetime2");

                    b.Property<long?>("SiteCode")
                        .HasColumnType("bigint");

                    b.Property<string>("SiteOrigin")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long?>("UserCode")
                        .HasColumnType("bigint");

                    b.HasKey("RedemptionId");

                    b.HasIndex("RedemptionId");

                    b.ToTable("Redemptions", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
